In [ ]:
# variable and datatypes
a = 5
b = 10
a, b = b, a
print(a, b)

10 5


In [ ]:
#Lists - Nested Lists

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(data[1][1])

flat_list = sum(data, [])
print(flat_list)

5
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#Dictionary - Complex Keys

coordinates = {(1, 2): 3, (3, 4): 7, (5, 6): 11}

def get_sum(coord_dict, x, y):
    return coord_dict.get((x, y))
print(get_sum(coordinates, 3, 4))

7


In [ ]:
#Functions - Nested Functions

def outer_function(a, b):
    def inner_function(x, y):
        return x**2 + y**2
    return inner_function(a, b)
print(outer_function(3, 4))


25


In [ ]:
#Functions - Lambda & Map

numbers = [1, 2, 3, 4, 5]
cubed_numbers = list(map(lambda x: x**3, numbers))
print(cubed_numbers)



[1, 8, 27, 64, 125]


In [ ]:
#Functions - Recursion

def sum_of_digits(n):
    if n == 0:
        return 0
    return n % 10 + sum_of_digits(n // 10)
print(sum_of_digits(1234))

10


In [ ]:
#List Comprehensions

numbers = [x for x in range(1, 101) if x % 5 == 0 and x % 3 != 0]
print(numbers)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]


In [ ]:
#Dictionary - Sorting by Values######

scores = {"Alice": 90, "Bob": 85, "Eve": 92}
sorted_scores = dict(sorted(scores.items(), key=lambda x: x[1], reverse=True))
print(sorted_scores)

{'Eve': 92, 'Alice': 90, 'Bob': 85}


In [ ]:
#Sets - Unique Characters

def unique_chars(s):
    unique_set = set(s)
    return unique_set, len(unique_set)
print(unique_chars("hello"))


({'o', 'e', 'l', 'h'}, 4)


In [ ]:
#Tuples - Finding Common Elements

t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
common_elements = set(t1) & set(t2)
print(common_elements)


{4, 5}


In [ ]:
#Dictionary - Reverse Key-Value Mapping

data = {"A": 1, "B": 2, "C": 3}
reversed_data = {v: k for k, v in data.items()}
print(reversed_data)


{1: 'A', 2: 'B', 3: 'C'}


In [ ]:

#Functions - Multiple Return Values

def math_operations(a, b):
    return a+b, a-b, a*b, a/b
print(math_operations(10, 2))



(12, 8, 20, 5.0)


In [ ]:
#List - Finding Second Largest Number

def second_largest(lst):
    first = second = float('-inf')
    for num in lst:
        if num > first:
            second, first = first, num
        elif num > second and num != first:
            second = num
    return second
print(second_largest([10, 20, 4, 45, 99]))


45


In [ ]:

#List - Pair Sum Problem

def find_pairs(lst, target):
    pairs = []
    for i in range(len(lst)):
        for j in range(i + 1, len(lst)):
            if lst[i] + lst[j] == target:
                pairs.append((lst[i], lst[j]))
    return pairs
print(find_pairs([2, 4, 3, 7, 1, 9], 10))

[(3, 7), (1, 9)]


In [ ]:
#Pandas - Filtering DataFrame
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
print(df[df['Age'] > 25])

    Name  Age  Score
1    Bob   27     90
3  David   32     88


In [ ]:
# Pandas - Group By Operation
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
avg=df.groupby('Department')['Salary'].mean()
print(avg)

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [ ]:
#NumPy - Create a 5x5 Matrix
import numpy as np
matrix = np.identity((5),dtype=int)
print(matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#NumPy - Element-wise Operations
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a + b)
print(a*b)
print(a^b)

[11 22 33 44]
[ 10  40  90 160]
[11 22 29 44]


In [ ]:
#NumPy - Find Index of Maximum Value
arr = np.array([10, 25, 39, 50, 19]).argmax()
print(arr)


3


In [ ]:
list1=[10, 25, 39, 50, 19]
list1.sort()
print(list1[-2])


39
